// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltmzhrgopdkrlsmigcpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0bXpocmdvcGRrcmxzbWlnY3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjM3OTgsImV4cCI6MjA2OTQzOTc5OH0.TJ_WFfIL84imTgMfjR4mheQZqLy1qPLLpr-bhlb9nRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});